# Generated by Django 4.0.4 on 2023-06-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipie_App', '0002_recipie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='recipie_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
