name: Playwright Tests in MyOtherRepo

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Run Playwright Tests
        uses: ./.github/workflows/playwright.yml
      
      
